### ISSUE TITLE
Code review comments

### ISSUE THREAD

**Issue by biggeng** [biggeng/CodisExport#1]
1. 请删除工程中无用的代码，如package codis中的多余文件
2. 在ExportData类中，使线程池的大小如果可以配置
3. 在ClientToCodisHelper类中，把row输出到文件，以及把文件传到hfs中，需要做两次磁盘I/O以及相应的网络开销。建议将此功能做一个flag开关，默认开关关闭。

**Comment by DoraemonXX** [comment]
Fixed
